services:
  quick-product-api:
    image: quick-product-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5051:80"
    links:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
